neo4j.uri=${NEO4J_URI:neo4j://127.0.0.1:7687}
neo4j.user=${NEO4J_USER:neo4j}
neo4j.password=${NEO4J_PASSWORD}
neo4j.database=${NEO4J_DATABASE:antifakenews}

server.port=8080
spring.application.name=antifakenews-backend
